Worlds:
- world
- world_nether
- world_the_end
Mobs:
  DisableEXP: false
  Bat: -1
  Bee: -1
  Blaze: 25
  Cat: -1
  CaveSpider: -1
  Chicken: -1
  Cod: -1
  Cow: -1
  Creeper: 10
  Dolphin: -1
  Donkey: -1
  Drowned: -1
  ElderGuardian: -1
  Enderman: 2
  Endermite: -1
  EnderDragon: -1
  Evoker: -1
  Fox: -1
  Ghast: -1
  Giant: -1
  Guardian: -1
  Hoglin: -1
  Horse: -1
  Husk: -1
  Illusioner: -1
  IronGolem: -1
  Llama: -1
  MagmaCube: -1
  Mule: -1
  MushroomCow: -1
  Ocelot: -1
  Panda: -1
  Parrot: -1
  Phantom: -1
  Pig: -1
  Piglin: 20
  PiglinBrute: 40
  Pillager: -1
  PolarBear: -1
  Pufferfish: -1
  Rabbit: -1
  Ravager: -1
  Salmon: -1
  Sheep: -1
  Shulker: -1
  Silverfish: -1
  Skeleton: 10
  SkeletonHorse: -1
  Slime: -1
  Snowman: -1
  Spider: 10
  Squid: -1
  Stray: -1
  Strider: -1
  TraderLlama: -1
  Tropicalfish: -1
  Turtle: -1
  Vex: -1
  Villager: -1
  Vindicator: -1
  WanderingTrader: -1
  Witch: -1
  Wither: -1
  WitherSkeleton: -1
  Wolf: -1
  Zoglin: -1
  Zombie: 10
  ZombieHorse: -1
  ZombieVillager: -1
  ZombifiedPiglin: -1
