LocalesVersion: 0.8.1

BloodMoonTitleBar: "&fBloodMoon"
DeathSuffix: "&fpodczas trwania &bBloodMoon&f!"
DaysBeforeBloodMoon: "&fDo następnego &bBloodMoon&f pozostało &b$d &fdni"
BloodMoonRightNow: "&fAktualnie trwa &bBloodMoon&f!"
BloodMoonTomorrow: "&fJutro nadchodzi &bBloodMoon&f!"
BloodMoonTonight: "&fDzisiejszej nocy niebo wydaje się &bciemniejsze&f..."
BloodMoonWarningTitle: "&b&lNadchodzi BloodMoon!"
BloodMoonWarningBody: "&fDoświadczenie zostaje zwielokrotnione, a moby mają lepsze dropy$n&fMoby są silniejsze i nakładają specjalne efekty"
BloodMoonEndingMessage: "&f&lBloodMoon się kończy... &bna razie&f"
DyingResultsInInventoryLoss: "&f&lŚmierć podczas &bBloodMoon&f skutkuje całkowitą utratą ekwipunku"
DyingResultsInExperienceLoss: "&f&lŚmierć podczas &bBloodMoon&f resetuje doświadczenie do zera"
PluginReloaded: "&fPlugin został pomyślnie &bprzeładowany&f"
NoBloodMoonInWorld: "&fW tym świecie aktualnie nie ma &bBloodMoon&f"
CommandNotFound: "&fKomenda &b$d &fnie istnieje!"
NoPermission: "&fNie masz &buprawnień&f do wykonania tej czynności!"
AllowedCommands: "&fDostępne komendy: &b$d"
BedNotAllowed: "&fNie możesz spać podczas &bBloodMoon&f"
WorldIsPermanentBloodMoon: "&fTen świat jest permanentnie pod wpływem &bBloodMoon&f!"
CannotStopBloodMoon: "&fNie możesz zatrzymać &bBloodMoon&f w tym świecie!"
GeneralError: "&fWystąpił &bbłąd&f podczas przetwarzania twojego żądania"
ZombieBossSpawned: "&f&l$b &fpojawił się!"
ZombieBossName: "Twardziel"
BossSlain: "&f&l$p &bpokonał &f$b!"
HordeArrived: "&fHorda mobów spadła na &b$p&f!"
NoPlayerOfName: "&fGracz o nazwie &b$p &fnie został znaleziony w świecie &b$w&f"
