pages:
  page1:
    title: "Skup"
    items:

      stone:
        material: STONE
        sell: 2

      cobblestone:
        material: COBBLESTONE
        sell: 1

      deepslate:
        material: DEEPSLATE
        sell: 2

      dirt:
        material: DIRT
        sell: 1

      grass_block:
        material: GRASS_BLOCK
        sell: 1

      sand:
        material: SAND
        sell: 1

      gravel:
        material: GRAVEL
        sell: 1

      clay_ball:
        material: CLAY_BALL
        sell: 3

      netherrack:
        material: NETHERRACK
        sell: 0.5

      end_stone:
        material: END_STONE
        sell: 2

      obsidian:
        material: OBSIDIAN
        sell: 20

      oak_log:
        material: OAK_LOG
        sell: 2

      spruce_log:
        material: SPRUCE_LOG
        sell: 2

      birch_log:
        material: BIRCH_LOG
        sell: 2

      jungle_log:
        material: JUNGLE_LOG
        sell: 2

      acacia_log:
        material: ACACIA_LOG
        sell: 2

      dark_oak_log:
        material: DARK_OAK_LOG
        sell: 2

      oak_planks:
        material: OAK_PLANKS
        sell: 2

      stick:
        material: STICK
        sell: 1

      coal:
        material: COAL
        sell: 10

      raw_iron:
        material: RAW_IRON
        sell: 15

      iron_ingot:
        material: IRON_INGOT
        sell: 25

      raw_copper:
        material: RAW_COPPER
        sell: 10

      copper_ingot:
        material: COPPER_INGOT
        sell: 18

      raw_gold:
        material: RAW_GOLD
        sell: 25

      gold_ingot:
        material: GOLD_INGOT
        sell: 40

      redstone:
        material: REDSTONE
        sell: 8

      lapis:
        material: LAPIS_LAZULI
        sell: 10

      quartz:
        material: QUARTZ
        sell: 12

      diamond:
        material: DIAMOND
        sell: 200

      emerald:
        material: EMERALD
        sell: 180

      netherite_scrap:
        material: NETHERITE_SCRAP
        sell: 600

      amethyst_shard:
        material: AMETHYST_SHARD
        sell: 15

      glowstone_dust:
        material: GLOWSTONE_DUST
        sell: 10

      rotten_flesh:
        material: ROTTEN_FLESH
        sell: 3

      bone:
        material: BONE
        sell: 6

      string:
        material: STRING
        sell: 5

      gunpowder:
        material: GUNPOWDER
        sell: 12

      spider_eye:
        material: SPIDER_EYE
        sell: 8

      ender_pearl:
        material: ENDER_PEARL
        sell: 35

      blaze_rod:
        material: BLAZE_ROD
        sell: 80

      slime_ball:
        material: SLIME_BALL
        sell: 30

      phantom_membrane:
        material: PHANTOM_MEMBRANE
        sell: 60

      nether_star:
        material: NETHER_STAR
        sell: 15000

      music_disc:
        material: MUSIC_DISC_13
        sell: 2500

      heads:
        material: PLAYER_HEAD
        sell: 500
  page2:
    title: "Skup"
    items:
      music_disc_13:
        material: MUSIC_DISC_13
        sell: 2500

      music_disc_cat:
        material: MUSIC_DISC_CAT
        sell: 2500

      music_disc_blocks:
        material: MUSIC_DISC_BLOCKS
        sell: 2500

      music_disc_chirp:
        material: MUSIC_DISC_CHIRP
        sell: 2500

      music_disc_far:
        material: MUSIC_DISC_FAR
        sell: 2500

      music_disc_mall:
        material: MUSIC_DISC_MALL
        sell: 2500

      music_disc_mellohi:
        material: MUSIC_DISC_MELLOHI
        sell: 2500

      music_disc_stal:
        material: MUSIC_DISC_STAL
        sell: 2500

      music_disc_strad:
        material: MUSIC_DISC_STRAD
        sell: 2500

      music_disc_ward:
        material: MUSIC_DISC_WARD
        sell: 2500

      music_disc_11:
        material: MUSIC_DISC_11
        sell: 2500

      music_disc_wait:
        material: MUSIC_DISC_WAIT
        sell: 2500

      music_disc_pigstep:
        material: MUSIC_DISC_PIGSTEP
        sell: 2500

      music_disc_otherside:
        material: MUSIC_DISC_OTHERSIDE
        sell: 2500

      music_disc_5:
        material: MUSIC_DISC_5
        sell: 2500

      music_disc_relic:
        material: MUSIC_DISC_RELIC
        sell: 2500
      bamboo:
        material: BAMBOO
        sell: 3

      sugar_cane:
        material: SUGAR_CANE
        sell: 5

      carrot:
        material: CARROT
        sell: 5

      potato:
        material: POTATO
        sell: 5

      beetroot:
        material: BEETROOT
        sell: 5

      wheat:
        material: WHEAT
        sell: 5

      hay_block:
        material: HAY_BLOCK
        sell: 5

      pumpkin:
        material: PUMPKIN
        sell: 20

      melon:
        material: MELON
        sell: 20

      wheat_seeds:
        material: WHEAT_SEEDS
        sell: 1

      beetroot_seeds:
        material: BEETROOT_SEEDS
        sell: 1

      pumpkin_seeds:
        material: PUMPKIN_SEEDS
        sell: 1

      melon_seeds:
        material: MELON_SEEDS
        sell: 1
